version: "3"

services:
  app:
    container_name: example_app
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: uvicorn server:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    environment:
      - DB_NAME=main
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - mysql
  mysql:
    container_name: example_mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST="%"
      - TZ="Asia/Tokyo"
