version: "3"

services:
  app:
    container_name: example_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_NAME=main
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=3306
      - SECRET_KEY=
  nginx:
    container_name: example_nginx
    build:
      context: ./docker/nginx
    ports:
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
