version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes: ./app:/app
    ports:
      - "8000:80"
  db:
    container_name: db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST="%"
      - TZ="Asia/Tokyo"
