version: "3"

services:
  app:
    container_name: example_app
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: bash -c "cd / && uvicorn app.server:app --host 0.0.0.0 --port 80 --reload --log-level debug"
    volumes:
      - ./app:/app
      - ./logs/app:/app/logs
    ports:
      - "3031:80"
    environment:
      - DB_HOST=mysql
      - DB_NAME=main
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=3306
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    depends_on:
      - mysql
  nginx:
    container_name: example_nginx
    build:
      context: ./docker/nginx
    ports:
      - "8000:8000"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
  mysql:
    container_name: example_mysql
    build:
      context: ./docker/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST="%"
      - TZ="Asia/Tokyo"
